# This file is auto-generated by generate_py.py. Do not edit manually.
from aloecrypt._plugin import _Plugin
from aloecrypt.api import *

# Resolve forward references
for _cls in [
    kem_api.KyberFullKEM,
    kem_api.KyberPublicKEM,
    kem_api.XKyberFullKEM,
    signatory_api.DilithiumSigner,
    signatory_api.DilithiumVerifier,
    signatory_api.XDilithiumSigner,
    party_api.Party,
    party_api.CounterParty,
    party_api.XParty,
    party_api.XCounterParty,
    session_api.AloecryptSession,
    session_api.XAloecryptSession,
    message_api.MsgHELLO,
    message_api.MsgSYN,
    message_api.MsgACK,
    message_api.MsgSYNACK,
    message_api.MsgWELCOME,
    message_api.MsgGOODBYE,
    message_api.MsgTRANSPORT,
    message_api.MsgRETRY,
    message_api.MsgROTATE,
    message_api.MsgRESYN,
    message_api.MsgERROR,
    builder_api.PartyINTRO,
    builder_api.PartyCIPHER,
    builder_api.FullCIPHER,
    builder_api.CounterPartySECRET,
    builder_api.PartyCHALLENGE,
    builder_api.PartyRESPONSE,
    builder_api.CounterPartyCHALLENGE,
    builder_api.FromSecretsInput,
    builder_api.SessionBuilder,
]:
    _cls.model_rebuild()

import aloecrypt.traits   # noqa: F401
import aloecrypt.functions  # noqa: F401

def aloecrypt_version() -> str:
    return _Plugin().call('aloecrypt_version', b'').decode()

from aloecrypt.functions import perform_handshake
