# This file is auto-generated by generate_py.py. Do not edit manually.
from aloecrypt._plugin import _wire_pack, _VarBytes, _VarStr, _Plugin
from aloecrypt.api import *

plugin = _Plugin()

# ── Into/From conversions ──

KyberFullKEM.to_kyber_public_kem = lambda self: KyberPublicKEM.from_wire_bytes(plugin.call("kem_api___kyberfullkem_into_kyberpublickem", _wire_pack(self)))
XKyberFullKEM.to_kyber_public_kem = lambda self: KyberPublicKEM.from_wire_bytes(plugin.call("kem_api___xkyberfullkem_into_kyberpublickem", _wire_pack(self)))
DilithiumVerifier.from_dilithium_signer = classmethod(lambda cls, val: DilithiumVerifier.from_wire_bytes(plugin.call("signatory_api___dilithiumverifier_from_dilithiumsigner", _wire_pack(val))))
DilithiumVerifier.from_xdilithium_signer = classmethod(lambda cls, val: DilithiumVerifier.from_wire_bytes(plugin.call("signatory_api___dilithiumverifier_from_xdilithiumsigner", _wire_pack(val))))

# ── Standalone functions ──

# ── util ──

def _ts_bytes_now():
    return plugin.call("util____ts_bytes_now", _wire_pack())

def _address(address_seed, addressing_material):
    return plugin.call("util____address", _wire_pack(_VarStr(address_seed), _VarBytes(addressing_material)))

def _hash(hash_seed, hashing_material):
    return plugin.call("util____hash", _wire_pack(_VarStr(hash_seed), _VarBytes(hashing_material)))

# ── password ──

def password_encrypt(bytes, aad, password, salt, nonce):
    return plugin.call("password___password_encrypt", _wire_pack(_VarBytes(bytes), _VarBytes(aad), _VarBytes(password), _VarBytes(salt), nonce))

def password_decrypt(bytes, aad, password, salt, nonce):
    return plugin.call("password___password_decrypt", _wire_pack(_VarBytes(bytes), _VarBytes(aad), _VarBytes(password), _VarBytes(salt), nonce))

# ── session.message ──

def send_encrypt(payload, sender, receiver, session_salt, receiver_nonce, receiver_address, sender_nonce, sender_address):
    return plugin.call("session_message___send_encrypt", _wire_pack(_VarBytes(payload), sender, receiver, session_salt, receiver_nonce, receiver_address, sender_nonce, sender_address))

def recv_decrypt(payload, sender, receiver, session_salt, receiver_nonce, receiver_address, sender_nonce, sender_address):
    return plugin.call("session_message___recv_decrypt", _wire_pack(_VarBytes(payload), sender, receiver, session_salt, receiver_nonce, receiver_address, sender_nonce, sender_address))

# ── session.util ──

def make_chacha_nonce(nonce_info_tag, nonce_seed, salt):
    return plugin.call("session_util___make_chacha_nonce", _wire_pack(_VarBytes(nonce_info_tag), _VarStr(nonce_seed), _VarBytes(salt)))

def nonce_pair(session_salt, session_seed, stable_seed):
    return plugin.call("session_util___nonce_pair", _wire_pack(session_salt, _VarStr(session_seed), _VarStr(stable_seed)))

def session_salt(n1, n2, a1, a2):
    return plugin.call("session_util___session_salt", _wire_pack(n1, n2, a1, a2))

def cipher_salt(seed, session_salt, decryptor_nonce, encryptor_nonce, encryptor_address):
    return plugin.call("session_util___cipher_salt", _wire_pack(_VarBytes(seed), session_salt, decryptor_nonce, encryptor_nonce, encryptor_address))

# ── Convenience functions ──

def perform_handshake(session_a, session_b):
    """Run a full HELLO -> SYN -> ACK -> SYNACK -> WELCOME handshake."""
    intro_a = session_a.make_party_intro()
    session_b.on_counterparty_intro(intro_a)
    intro_b = session_b.make_party_intro()
    cipher_b = session_b.make_party_cipher()
    session_a.on_counterparty_intro(intro_b)
    session_a.on_counterparty_cipher(cipher_b)
    cipher_a = session_a.make_party_cipher()
    challenge_a = session_a.make_party_challenge()
    session_b.on_counterparty_cipher(cipher_a)
    session_b.on_counterparty_challenge(challenge_a)
    challenge_b = session_b.make_party_challenge()
    response_b = session_b.make_party_challenge_response()
    session_a.on_counterparty_challenge(challenge_b)
    session_a.on_counterparty_challenge_response(response_b)
    response_a = session_a.make_party_challenge_response()
    session_b.on_counterparty_challenge_response(response_a)
    return session_a.build(), session_b.build()
