# This file is auto-generated by generate_py.py. Do not edit manually.
from aloecrypt._plugin import _wire_pack, _VarBytes, _VarStr, _Plugin
from aloecrypt.api import *

plugin = _Plugin()

def _rebuild(obj, data_bytes, cls):
    new = cls.from_wire_bytes(data_bytes)
    obj.__dict__.update(new.__dict__)
    return obj

# ── XKyberFullKEM :: AloecryptAddressable ──

XKyberFullKEM.generation = property(lambda self: int.from_bytes(plugin.call("kem_api___xkyberfullkem_generation", _wire_pack(self)), 'little'))
XKyberFullKEM.address = property(lambda self: plugin.call("kem_api___xkyberfullkem_address", _wire_pack(self)))
XKyberFullKEM.auth_address = property(lambda self: plugin.call("kem_api___xkyberfullkem_auth_address", _wire_pack(self)))
XKyberFullKEM.root_address = property(lambda self: plugin.call("kem_api___xkyberfullkem_root_address", _wire_pack(self)))
XKyberFullKEM.addressing_material = property(lambda self: plugin.call("kem_api___xkyberfullkem_addressing_material", _wire_pack(self)))
XKyberFullKEM.auth_addressing_material = property(lambda self: plugin.call("kem_api___xkyberfullkem_auth_addressing_material", _wire_pack(self)))
XKyberFullKEM.is_root = property(lambda self: bool(plugin.call("kem_api___xkyberfullkem_is_root", _wire_pack(self))[0]))

# ── KyberFullKEM :: AloecryptAddressable ──

KyberFullKEM.generation = property(lambda self: int.from_bytes(plugin.call("kem_api___kyberfullkem_generation", _wire_pack(self)), 'little'))
KyberFullKEM.address = property(lambda self: plugin.call("kem_api___kyberfullkem_address", _wire_pack(self)))
KyberFullKEM.auth_address = property(lambda self: plugin.call("kem_api___kyberfullkem_auth_address", _wire_pack(self)))
KyberFullKEM.root_address = property(lambda self: plugin.call("kem_api___kyberfullkem_root_address", _wire_pack(self)))
KyberFullKEM.addressing_material = property(lambda self: plugin.call("kem_api___kyberfullkem_addressing_material", _wire_pack(self)))
KyberFullKEM.auth_addressing_material = property(lambda self: plugin.call("kem_api___kyberfullkem_auth_addressing_material", _wire_pack(self)))
KyberFullKEM.is_root = property(lambda self: bool(plugin.call("kem_api___kyberfullkem_is_root", _wire_pack(self))[0]))

# ── KyberPublicKEM :: AloecryptAddressable ──

KyberPublicKEM.generation = property(lambda self: int.from_bytes(plugin.call("kem_api___kyberpublickem_generation", _wire_pack(self)), 'little'))
KyberPublicKEM.address = property(lambda self: plugin.call("kem_api___kyberpublickem_address", _wire_pack(self)))
KyberPublicKEM.auth_address = property(lambda self: plugin.call("kem_api___kyberpublickem_auth_address", _wire_pack(self)))
KyberPublicKEM.root_address = property(lambda self: plugin.call("kem_api___kyberpublickem_root_address", _wire_pack(self)))
KyberPublicKEM.addressing_material = property(lambda self: plugin.call("kem_api___kyberpublickem_addressing_material", _wire_pack(self)))
KyberPublicKEM.auth_addressing_material = property(lambda self: plugin.call("kem_api___kyberpublickem_auth_addressing_material", _wire_pack(self)))
KyberPublicKEM.is_root = property(lambda self: bool(plugin.call("kem_api___kyberpublickem_is_root", _wire_pack(self))[0]))

# ── KyberFullKEM :: AloecryptDecapsulator ──

KyberFullKEM.decapsulation_key = property(lambda self: plugin.call("kem_api___kyberfullkem_decapsulation_key", _wire_pack(self)))
KyberFullKEM.decapsulate = lambda self, cipher: plugin.call("kem_api___kyberfullkem_decapsulate", _wire_pack(self, cipher))

# ── KyberFullKEM :: AloecryptEmpty ──

KyberFullKEM.empty = classmethod(lambda cls: KyberFullKEM.from_wire_bytes(plugin.call("kem_api___kyberfullkem_empty", b"")))
KyberFullKEM.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("kem_api___kyberfullkem_byte_sz", _wire_pack()), 'little'))
KyberFullKEM.to_bytes = property(lambda self: plugin.call("kem_api___kyberfullkem_to_bytes", _wire_pack(self)))
KyberFullKEM.from_bytes = classmethod(lambda cls, bytes: KyberFullKEM.from_wire_bytes(plugin.call("kem_api___kyberfullkem_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── XKyberFullKEM :: AloecryptEmpty ──

XKyberFullKEM.empty = classmethod(lambda cls: XKyberFullKEM.from_wire_bytes(plugin.call("kem_api___xkyberfullkem_empty", b"")))
XKyberFullKEM.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("kem_api___xkyberfullkem_byte_sz", _wire_pack()), 'little'))
XKyberFullKEM.to_bytes = property(lambda self: plugin.call("kem_api___xkyberfullkem_to_bytes", _wire_pack(self)))
XKyberFullKEM.from_bytes = classmethod(lambda cls, bytes: XKyberFullKEM.from_wire_bytes(plugin.call("kem_api___xkyberfullkem_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── KyberPublicKEM :: AloecryptEmpty ──

KyberPublicKEM.empty = classmethod(lambda cls: KyberPublicKEM.from_wire_bytes(plugin.call("kem_api___kyberpublickem_empty", b"")))
KyberPublicKEM.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("kem_api___kyberpublickem_byte_sz", _wire_pack()), 'little'))
KyberPublicKEM.to_bytes = property(lambda self: plugin.call("kem_api___kyberpublickem_to_bytes", _wire_pack(self)))
KyberPublicKEM.from_bytes = classmethod(lambda cls, bytes: KyberPublicKEM.from_wire_bytes(plugin.call("kem_api___kyberpublickem_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── KyberPublicKEM :: AloecryptEncapsulator ──

KyberPublicKEM.encapsulation_key = property(lambda self: plugin.call("kem_api___kyberpublickem_encapsulation_key", _wire_pack(self)))
KyberPublicKEM.encapsulate = lambda self: plugin.call("kem_api___kyberpublickem_encapsulate", _wire_pack(self, -1))

# ── KyberFullKEM :: AloecryptEncapsulator ──

KyberFullKEM.encapsulation_key = property(lambda self: plugin.call("kem_api___kyberfullkem_encapsulation_key", _wire_pack(self)))
KyberFullKEM.encapsulate = lambda self: plugin.call("kem_api___kyberfullkem_encapsulate", _wire_pack(self, -1))

# ── XKyberFullKEM :: AloecryptXHashable ──

XKyberFullKEM.hash = property(lambda self: plugin.call("kem_api___xkyberfullkem_hash", _wire_pack(self)))
XKyberFullKEM.x_hash = property(lambda self: plugin.call("kem_api___xkyberfullkem_x_hash", _wire_pack(self)))
XKyberFullKEM.x_hashing_material = property(lambda self: plugin.call("kem_api___xkyberfullkem_x_hashing_material", _wire_pack(self)))

# ── KyberPublicKEM :: AloecryptHashable ──

KyberPublicKEM.hash = property(lambda self: plugin.call("kem_api___kyberpublickem_hash", _wire_pack(self)))
KyberPublicKEM.hashing_material = property(lambda self: plugin.call("kem_api___kyberpublickem_hashing_material", _wire_pack(self)))

# ── KyberFullKEM :: AloecryptHashable ──

KyberFullKEM.hash = property(lambda self: plugin.call("kem_api___kyberfullkem_hash", _wire_pack(self)))
KyberFullKEM.hashing_material = property(lambda self: plugin.call("kem_api___kyberfullkem_hashing_material", _wire_pack(self)))

# ── KyberFullKEM :: AloecryptHashableKeypair ──

KyberFullKEM.pub_hash = property(lambda self: plugin.call("kem_api___kyberfullkem_pub_hash", _wire_pack(self)))
KyberFullKEM.priv_hash = property(lambda self: plugin.call("kem_api___kyberfullkem_priv_hash", _wire_pack(self)))

# ── XKyberFullKEM :: AloecryptHashableKeypair ──

XKyberFullKEM.pub_hash = property(lambda self: plugin.call("kem_api___xkyberfullkem_pub_hash", _wire_pack(self)))
XKyberFullKEM.priv_hash = property(lambda self: plugin.call("kem_api___xkyberfullkem_priv_hash", _wire_pack(self)))

# ── KyberPublicKEM :: AloecryptHashablePubkey ──

KyberPublicKEM.pub_hash = property(lambda self: plugin.call("kem_api___kyberpublickem_pub_hash", _wire_pack(self)))

# ── KyberFullKEM :: AloecryptPasswordPEM ──

KyberFullKEM.pem_hdr_tag = staticmethod(lambda: plugin.call("kem_api___kyberfullkem_pem_hdr_tag", _wire_pack()).decode())
KyberFullKEM.pem_ftr_tag = staticmethod(lambda: plugin.call("kem_api___kyberfullkem_pem_ftr_tag", _wire_pack()).decode())
KyberFullKEM.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("kem_api___kyberfullkem_pem_sz", _wire_pack()), 'little'))
KyberFullKEM.x_pem = lambda self, password, salt: plugin.call("kem_api___kyberfullkem_x_pem", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)).decode()
KyberFullKEM.x_loads = classmethod(lambda cls, pem, password, salt: KyberFullKEM.from_wire_bytes(plugin.call("kem_api___kyberfullkem_x_loads", _wire_pack(_VarStr(pem), _VarBytes(password), _VarBytes(salt)))))
KyberFullKEM.x_pub_loads = staticmethod(lambda pem: KyberPublicKEM.from_wire_bytes(plugin.call("kem_api___kyberfullkem_x_pub_loads", _wire_pack(_VarStr(pem)))))

# ── KyberFullKEM :: AloecryptPasswordLockable ──

KyberFullKEM.lock_with_password = lambda self, password, salt: XKyberFullKEM.from_wire_bytes(plugin.call("kem_api___kyberfullkem_lock_with_password", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)))
KyberFullKEM.unlock_with_password = classmethod(lambda cls, x_obj, password, salt: KyberFullKEM.from_wire_bytes(plugin.call("kem_api___kyberfullkem_unlock_with_password", _wire_pack(x_obj, _VarBytes(password), _VarBytes(salt)))))

# ── XKyberFullKEM :: AloecryptPEM ──

XKyberFullKEM.pem_hdr_tag = staticmethod(lambda: plugin.call("kem_api___xkyberfullkem_pem_hdr_tag", _wire_pack()).decode())
XKyberFullKEM.pem_ftr_tag = staticmethod(lambda: plugin.call("kem_api___xkyberfullkem_pem_ftr_tag", _wire_pack()).decode())
XKyberFullKEM.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("kem_api___xkyberfullkem_pem_sz", _wire_pack()), 'little'))
XKyberFullKEM.pem = property(lambda self: plugin.call("kem_api___xkyberfullkem_pem", _wire_pack(self)).decode())
XKyberFullKEM.loads = classmethod(lambda cls, pem: XKyberFullKEM.from_wire_bytes(plugin.call("kem_api___xkyberfullkem_loads", _wire_pack(_VarStr(pem)))))

# ── KyberPublicKEM :: AloecryptPEM ──

KyberPublicKEM.pem_hdr_tag = staticmethod(lambda: plugin.call("kem_api___kyberpublickem_pem_hdr_tag", _wire_pack()).decode())
KyberPublicKEM.pem_ftr_tag = staticmethod(lambda: plugin.call("kem_api___kyberpublickem_pem_ftr_tag", _wire_pack()).decode())
KyberPublicKEM.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("kem_api___kyberpublickem_pem_sz", _wire_pack()), 'little'))
KyberPublicKEM.pem = property(lambda self: plugin.call("kem_api___kyberpublickem_pem", _wire_pack(self)).decode())
KyberPublicKEM.loads = classmethod(lambda cls, pem: KyberPublicKEM.from_wire_bytes(plugin.call("kem_api___kyberpublickem_loads", _wire_pack(_VarStr(pem)))))

# ── KyberFullKEM :: AloecryptSignable ──

KyberFullKEM.signature = property(lambda self: plugin.call("kem_api___kyberfullkem_signature", _wire_pack(self)))
KyberFullKEM.signed_by = property(lambda self: plugin.call("kem_api___kyberfullkem_signed_by", _wire_pack(self)))
KyberFullKEM.signing_material = property(lambda self: plugin.call("kem_api___kyberfullkem_signing_material", _wire_pack(self)))

# ── KyberPublicKEM :: AloecryptSignable ──

KyberPublicKEM.signature = property(lambda self: plugin.call("kem_api___kyberpublickem_signature", _wire_pack(self)))
KyberPublicKEM.signed_by = property(lambda self: plugin.call("kem_api___kyberpublickem_signed_by", _wire_pack(self)))
KyberPublicKEM.signing_material = property(lambda self: plugin.call("kem_api___kyberpublickem_signing_material", _wire_pack(self)))

# ── Party :: AloecryptAddressable ──

Party.generation = property(lambda self: int.from_bytes(plugin.call("party_api___party_generation", _wire_pack(self)), 'little'))
Party.address = property(lambda self: plugin.call("party_api___party_address", _wire_pack(self)))
Party.auth_address = property(lambda self: plugin.call("party_api___party_auth_address", _wire_pack(self)))
Party.root_address = property(lambda self: plugin.call("party_api___party_root_address", _wire_pack(self)))
Party.addressing_material = property(lambda self: plugin.call("party_api___party_addressing_material", _wire_pack(self)))
Party.auth_addressing_material = property(lambda self: plugin.call("party_api___party_auth_addressing_material", _wire_pack(self)))
Party.is_root = property(lambda self: bool(plugin.call("party_api___party_is_root", _wire_pack(self))[0]))

# ── CounterParty :: AloecryptAddressable ──

CounterParty.generation = property(lambda self: int.from_bytes(plugin.call("party_api___counterparty_generation", _wire_pack(self)), 'little'))
CounterParty.auth_address = property(lambda self: plugin.call("party_api___counterparty_auth_address", _wire_pack(self)))
CounterParty.root_address = property(lambda self: plugin.call("party_api___counterparty_root_address", _wire_pack(self)))
CounterParty.addressing_material = property(lambda self: plugin.call("party_api___counterparty_addressing_material", _wire_pack(self)))
CounterParty.auth_addressing_material = property(lambda self: plugin.call("party_api___counterparty_auth_addressing_material", _wire_pack(self)))
CounterParty.is_root = property(lambda self: bool(plugin.call("party_api___counterparty_is_root", _wire_pack(self))[0]))

# ── SessionBuilder :: AloecryptAddressable ──

SessionBuilder.generation = property(lambda self: int.from_bytes(plugin.call("builder_api___sessionbuilder_generation", _wire_pack(self)), 'little'))
SessionBuilder.address = property(lambda self: plugin.call("builder_api___sessionbuilder_address", _wire_pack(self)))
SessionBuilder.auth_address = property(lambda self: plugin.call("builder_api___sessionbuilder_auth_address", _wire_pack(self)))
SessionBuilder.root_address = property(lambda self: plugin.call("builder_api___sessionbuilder_root_address", _wire_pack(self)))
SessionBuilder.addressing_material = property(lambda self: plugin.call("builder_api___sessionbuilder_addressing_material", _wire_pack(self)))
SessionBuilder.auth_addressing_material = property(lambda self: plugin.call("builder_api___sessionbuilder_auth_addressing_material", _wire_pack(self)))
SessionBuilder.is_root = property(lambda self: bool(plugin.call("builder_api___sessionbuilder_is_root", _wire_pack(self))[0]))

# ── AloecryptSession :: AloecryptAddressable ──

AloecryptSession.generation = property(lambda self: int.from_bytes(plugin.call("session_api___aloecryptsession_generation", _wire_pack(self)), 'little'))
AloecryptSession.address = property(lambda self: plugin.call("session_api___aloecryptsession_address", _wire_pack(self)))
AloecryptSession.auth_address = property(lambda self: plugin.call("session_api___aloecryptsession_auth_address", _wire_pack(self)))
AloecryptSession.root_address = property(lambda self: plugin.call("session_api___aloecryptsession_root_address", _wire_pack(self)))
AloecryptSession.addressing_material = property(lambda self: plugin.call("session_api___aloecryptsession_addressing_material", _wire_pack(self)))
AloecryptSession.auth_addressing_material = property(lambda self: plugin.call("session_api___aloecryptsession_auth_addressing_material", _wire_pack(self)))
AloecryptSession.is_root = property(lambda self: bool(plugin.call("session_api___aloecryptsession_is_root", _wire_pack(self))[0]))

# ── PartyINTRO :: IPartyINTRO ──

PartyINTRO.make_salt = staticmethod(lambda party_a, party_b: plugin.call("builder_api___partyintro_make_salt", _wire_pack(party_a, party_b)))
PartyINTRO.make_cipher = lambda self, signature: FullCIPHER.from_wire_bytes(plugin.call("builder_api___partyintro_make_cipher", _wire_pack(self, signature, -1)))

# ── SessionBuilder :: ISessionBuilder ──

SessionBuilder.new = classmethod(lambda cls, counterparty_address, delegate_signer: SessionBuilder.from_wire_bytes(plugin.call("builder_api___sessionbuilder_new", _wire_pack(counterparty_address, delegate_signer, -1))))

# ── SessionBuilder :: AloecryptSessionBuilder ──

SessionBuilder.make_party_intro = lambda self: PartyINTRO.from_wire_bytes(plugin.call("builder_api___sessionbuilder_make_party_intro", _wire_pack(self)))
SessionBuilder.make_party_challenge = lambda self: PartyCHALLENGE.from_wire_bytes(plugin.call("builder_api___sessionbuilder_make_party_challenge", _wire_pack(self)))
SessionBuilder.make_party_challenge_response = lambda self: PartyRESPONSE.from_wire_bytes(plugin.call("builder_api___sessionbuilder_make_party_challenge_response", _wire_pack(self)))
SessionBuilder.make_party_cipher = lambda self: PartyCIPHER.from_wire_bytes(plugin.call("builder_api___sessionbuilder_make_party_cipher", _wire_pack(self)))
SessionBuilder.on_counterparty_intro = lambda self, counterparty_intro: _rebuild(self, plugin.call("builder_api___sessionbuilder_on_counterparty_intro", _wire_pack(self, counterparty_intro, -1)), SessionBuilder)
SessionBuilder.on_counterparty_cipher = lambda self, counterparty_cipher: _rebuild(self, plugin.call("builder_api___sessionbuilder_on_counterparty_cipher", _wire_pack(self, counterparty_cipher)), SessionBuilder)
SessionBuilder.on_counterparty_challenge = lambda self, counterparty_challenge: _rebuild(self, plugin.call("builder_api___sessionbuilder_on_counterparty_challenge", _wire_pack(self, counterparty_challenge)), SessionBuilder)
SessionBuilder.on_counterparty_challenge_response = lambda self, counterparty_challenge_response: _rebuild(self, plugin.call("builder_api___sessionbuilder_on_counterparty_challenge_response", _wire_pack(self, counterparty_challenge_response)), SessionBuilder)
SessionBuilder.build = lambda self: AloecryptSession.from_wire_bytes(plugin.call("builder_api___sessionbuilder_build", _wire_pack(self)))

# ── PartyINTRO :: AloecryptEmpty ──

PartyINTRO.empty = classmethod(lambda cls: PartyINTRO.from_wire_bytes(plugin.call("builder_api___partyintro_empty", b"")))
PartyINTRO.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___partyintro_byte_sz", _wire_pack()), 'little'))
PartyINTRO.to_bytes = property(lambda self: plugin.call("builder_api___partyintro_to_bytes", _wire_pack(self)))
PartyINTRO.from_bytes = classmethod(lambda cls, bytes: PartyINTRO.from_wire_bytes(plugin.call("builder_api___partyintro_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── PartyCIPHER :: AloecryptEmpty ──

PartyCIPHER.empty = classmethod(lambda cls: PartyCIPHER.from_wire_bytes(plugin.call("builder_api___partycipher_empty", b"")))
PartyCIPHER.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___partycipher_byte_sz", _wire_pack()), 'little'))
PartyCIPHER.to_bytes = property(lambda self: plugin.call("builder_api___partycipher_to_bytes", _wire_pack(self)))
PartyCIPHER.from_bytes = classmethod(lambda cls, bytes: PartyCIPHER.from_wire_bytes(plugin.call("builder_api___partycipher_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── FullCIPHER :: AloecryptEmpty ──

FullCIPHER.empty = classmethod(lambda cls: FullCIPHER.from_wire_bytes(plugin.call("builder_api___fullcipher_empty", b"")))
FullCIPHER.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___fullcipher_byte_sz", _wire_pack()), 'little'))
FullCIPHER.to_bytes = property(lambda self: plugin.call("builder_api___fullcipher_to_bytes", _wire_pack(self)))
FullCIPHER.from_bytes = classmethod(lambda cls, bytes: FullCIPHER.from_wire_bytes(plugin.call("builder_api___fullcipher_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── CounterPartySECRET :: AloecryptEmpty ──

CounterPartySECRET.empty = classmethod(lambda cls: CounterPartySECRET.from_wire_bytes(plugin.call("builder_api___counterpartysecret_empty", b"")))
CounterPartySECRET.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___counterpartysecret_byte_sz", _wire_pack()), 'little'))
CounterPartySECRET.to_bytes = property(lambda self: plugin.call("builder_api___counterpartysecret_to_bytes", _wire_pack(self)))
CounterPartySECRET.from_bytes = classmethod(lambda cls, bytes: CounterPartySECRET.from_wire_bytes(plugin.call("builder_api___counterpartysecret_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── PartyCHALLENGE :: AloecryptEmpty ──

PartyCHALLENGE.empty = classmethod(lambda cls: PartyCHALLENGE.from_wire_bytes(plugin.call("builder_api___partychallenge_empty", b"")))
PartyCHALLENGE.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___partychallenge_byte_sz", _wire_pack()), 'little'))
PartyCHALLENGE.to_bytes = property(lambda self: plugin.call("builder_api___partychallenge_to_bytes", _wire_pack(self)))
PartyCHALLENGE.from_bytes = classmethod(lambda cls, bytes: PartyCHALLENGE.from_wire_bytes(plugin.call("builder_api___partychallenge_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── PartyRESPONSE :: AloecryptEmpty ──

PartyRESPONSE.empty = classmethod(lambda cls: PartyRESPONSE.from_wire_bytes(plugin.call("builder_api___partyresponse_empty", b"")))
PartyRESPONSE.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___partyresponse_byte_sz", _wire_pack()), 'little'))
PartyRESPONSE.to_bytes = property(lambda self: plugin.call("builder_api___partyresponse_to_bytes", _wire_pack(self)))
PartyRESPONSE.from_bytes = classmethod(lambda cls, bytes: PartyRESPONSE.from_wire_bytes(plugin.call("builder_api___partyresponse_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── CounterPartyCHALLENGE :: AloecryptEmpty ──

CounterPartyCHALLENGE.empty = classmethod(lambda cls: CounterPartyCHALLENGE.from_wire_bytes(plugin.call("builder_api___counterpartychallenge_empty", b"")))
CounterPartyCHALLENGE.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___counterpartychallenge_byte_sz", _wire_pack()), 'little'))
CounterPartyCHALLENGE.to_bytes = property(lambda self: plugin.call("builder_api___counterpartychallenge_to_bytes", _wire_pack(self)))
CounterPartyCHALLENGE.from_bytes = classmethod(lambda cls, bytes: CounterPartyCHALLENGE.from_wire_bytes(plugin.call("builder_api___counterpartychallenge_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── FromSecretsInput :: AloecryptEmpty ──

FromSecretsInput.empty = classmethod(lambda cls: FromSecretsInput.from_wire_bytes(plugin.call("builder_api___fromsecretsinput_empty", b"")))
FromSecretsInput.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___fromsecretsinput_byte_sz", _wire_pack()), 'little'))
FromSecretsInput.to_bytes = property(lambda self: plugin.call("builder_api___fromsecretsinput_to_bytes", _wire_pack(self)))
FromSecretsInput.from_bytes = classmethod(lambda cls, bytes: FromSecretsInput.from_wire_bytes(plugin.call("builder_api___fromsecretsinput_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── SessionBuilder :: AloecryptEmpty ──

SessionBuilder.empty = classmethod(lambda cls: SessionBuilder.from_wire_bytes(plugin.call("builder_api___sessionbuilder_empty", b"")))
SessionBuilder.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("builder_api___sessionbuilder_byte_sz", _wire_pack()), 'little'))
SessionBuilder.to_bytes = property(lambda self: plugin.call("builder_api___sessionbuilder_to_bytes", _wire_pack(self)))
SessionBuilder.from_bytes = classmethod(lambda cls, bytes: SessionBuilder.from_wire_bytes(plugin.call("builder_api___sessionbuilder_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgHELLO :: AloecryptEmpty ──

MsgHELLO.empty = classmethod(lambda cls: MsgHELLO.from_wire_bytes(plugin.call("message_api___msghello_empty", b"")))
MsgHELLO.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msghello_byte_sz", _wire_pack()), 'little'))
MsgHELLO.to_bytes = property(lambda self: plugin.call("message_api___msghello_to_bytes", _wire_pack(self)))
MsgHELLO.from_bytes = classmethod(lambda cls, bytes: MsgHELLO.from_wire_bytes(plugin.call("message_api___msghello_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgSYN :: AloecryptEmpty ──

MsgSYN.empty = classmethod(lambda cls: MsgSYN.from_wire_bytes(plugin.call("message_api___msgsyn_empty", b"")))
MsgSYN.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgsyn_byte_sz", _wire_pack()), 'little'))
MsgSYN.to_bytes = property(lambda self: plugin.call("message_api___msgsyn_to_bytes", _wire_pack(self)))
MsgSYN.from_bytes = classmethod(lambda cls, bytes: MsgSYN.from_wire_bytes(plugin.call("message_api___msgsyn_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgACK :: AloecryptEmpty ──

MsgACK.empty = classmethod(lambda cls: MsgACK.from_wire_bytes(plugin.call("message_api___msgack_empty", b"")))
MsgACK.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgack_byte_sz", _wire_pack()), 'little'))
MsgACK.to_bytes = property(lambda self: plugin.call("message_api___msgack_to_bytes", _wire_pack(self)))
MsgACK.from_bytes = classmethod(lambda cls, bytes: MsgACK.from_wire_bytes(plugin.call("message_api___msgack_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgSYNACK :: AloecryptEmpty ──

MsgSYNACK.empty = classmethod(lambda cls: MsgSYNACK.from_wire_bytes(plugin.call("message_api___msgsynack_empty", b"")))
MsgSYNACK.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgsynack_byte_sz", _wire_pack()), 'little'))
MsgSYNACK.to_bytes = property(lambda self: plugin.call("message_api___msgsynack_to_bytes", _wire_pack(self)))
MsgSYNACK.from_bytes = classmethod(lambda cls, bytes: MsgSYNACK.from_wire_bytes(plugin.call("message_api___msgsynack_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgWELCOME :: AloecryptEmpty ──

MsgWELCOME.empty = classmethod(lambda cls: MsgWELCOME.from_wire_bytes(plugin.call("message_api___msgwelcome_empty", b"")))
MsgWELCOME.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgwelcome_byte_sz", _wire_pack()), 'little'))
MsgWELCOME.to_bytes = property(lambda self: plugin.call("message_api___msgwelcome_to_bytes", _wire_pack(self)))
MsgWELCOME.from_bytes = classmethod(lambda cls, bytes: MsgWELCOME.from_wire_bytes(plugin.call("message_api___msgwelcome_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgGOODBYE :: AloecryptEmpty ──

MsgGOODBYE.empty = classmethod(lambda cls: MsgGOODBYE.from_wire_bytes(plugin.call("message_api___msggoodbye_empty", b"")))
MsgGOODBYE.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msggoodbye_byte_sz", _wire_pack()), 'little'))
MsgGOODBYE.to_bytes = property(lambda self: plugin.call("message_api___msggoodbye_to_bytes", _wire_pack(self)))
MsgGOODBYE.from_bytes = classmethod(lambda cls, bytes: MsgGOODBYE.from_wire_bytes(plugin.call("message_api___msggoodbye_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgRETRY :: AloecryptEmpty ──

MsgRETRY.empty = classmethod(lambda cls: MsgRETRY.from_wire_bytes(plugin.call("message_api___msgretry_empty", b"")))
MsgRETRY.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgretry_byte_sz", _wire_pack()), 'little'))
MsgRETRY.to_bytes = property(lambda self: plugin.call("message_api___msgretry_to_bytes", _wire_pack(self)))
MsgRETRY.from_bytes = classmethod(lambda cls, bytes: MsgRETRY.from_wire_bytes(plugin.call("message_api___msgretry_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── MsgRESYN :: AloecryptEmpty ──

MsgRESYN.empty = classmethod(lambda cls: MsgRESYN.from_wire_bytes(plugin.call("message_api___msgresyn_empty", b"")))
MsgRESYN.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgresyn_byte_sz", _wire_pack()), 'little'))
MsgRESYN.to_bytes = property(lambda self: plugin.call("message_api___msgresyn_to_bytes", _wire_pack(self)))
MsgRESYN.from_bytes = classmethod(lambda cls, bytes: MsgRESYN.from_wire_bytes(plugin.call("message_api___msgresyn_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── Party :: AloecryptEmpty ──

Party.empty = classmethod(lambda cls: Party.from_wire_bytes(plugin.call("party_api___party_empty", b"")))
Party.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("party_api___party_byte_sz", _wire_pack()), 'little'))
Party.to_bytes = property(lambda self: plugin.call("party_api___party_to_bytes", _wire_pack(self)))
Party.from_bytes = classmethod(lambda cls, bytes: Party.from_wire_bytes(plugin.call("party_api___party_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── CounterParty :: AloecryptEmpty ──

CounterParty.empty = classmethod(lambda cls: CounterParty.from_wire_bytes(plugin.call("party_api___counterparty_empty", b"")))
CounterParty.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("party_api___counterparty_byte_sz", _wire_pack()), 'little'))
CounterParty.to_bytes = property(lambda self: plugin.call("party_api___counterparty_to_bytes", _wire_pack(self)))
CounterParty.from_bytes = classmethod(lambda cls, bytes: CounterParty.from_wire_bytes(plugin.call("party_api___counterparty_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── AloecryptSession :: AloecryptEmpty ──

AloecryptSession.empty = classmethod(lambda cls: AloecryptSession.from_wire_bytes(plugin.call("session_api___aloecryptsession_empty", b"")))
AloecryptSession.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("session_api___aloecryptsession_byte_sz", _wire_pack()), 'little'))
AloecryptSession.to_bytes = property(lambda self: plugin.call("session_api___aloecryptsession_to_bytes", _wire_pack(self)))
AloecryptSession.from_bytes = classmethod(lambda cls, bytes: AloecryptSession.from_wire_bytes(plugin.call("session_api___aloecryptsession_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── XParty :: AloecryptEmpty ──

XParty.empty = classmethod(lambda cls: XParty.from_wire_bytes(plugin.call("party_api___xparty_empty", b"")))
XParty.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("party_api___xparty_byte_sz", _wire_pack()), 'little'))
XParty.to_bytes = property(lambda self: plugin.call("party_api___xparty_to_bytes", _wire_pack(self)))
XParty.from_bytes = classmethod(lambda cls, bytes: XParty.from_wire_bytes(plugin.call("party_api___xparty_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── XCounterParty :: AloecryptEmpty ──

XCounterParty.empty = classmethod(lambda cls: XCounterParty.from_wire_bytes(plugin.call("party_api___xcounterparty_empty", b"")))
XCounterParty.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("party_api___xcounterparty_byte_sz", _wire_pack()), 'little'))
XCounterParty.to_bytes = property(lambda self: plugin.call("party_api___xcounterparty_to_bytes", _wire_pack(self)))
XCounterParty.from_bytes = classmethod(lambda cls, bytes: XCounterParty.from_wire_bytes(plugin.call("party_api___xcounterparty_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── XAloecryptSession :: AloecryptEmpty ──

XAloecryptSession.empty = classmethod(lambda cls: XAloecryptSession.from_wire_bytes(plugin.call("session_api___xaloecryptsession_empty", b"")))
XAloecryptSession.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("session_api___xaloecryptsession_byte_sz", _wire_pack()), 'little'))
XAloecryptSession.to_bytes = property(lambda self: plugin.call("session_api___xaloecryptsession_to_bytes", _wire_pack(self)))
XAloecryptSession.from_bytes = classmethod(lambda cls, bytes: XAloecryptSession.from_wire_bytes(plugin.call("session_api___xaloecryptsession_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── PartyINTRO :: AloecryptHashable ──

PartyINTRO.hash = property(lambda self: plugin.call("builder_api___partyintro_hash", _wire_pack(self)))
PartyINTRO.hashing_material = property(lambda self: plugin.call("builder_api___partyintro_hashing_material", _wire_pack(self)))

# ── PartyCIPHER :: AloecryptHashable ──

PartyCIPHER.hash = property(lambda self: plugin.call("builder_api___partycipher_hash", _wire_pack(self)))
PartyCIPHER.hashing_material = property(lambda self: plugin.call("builder_api___partycipher_hashing_material", _wire_pack(self)))

# ── FullCIPHER :: AloecryptHashable ──

FullCIPHER.hash = property(lambda self: plugin.call("builder_api___fullcipher_hash", _wire_pack(self)))
FullCIPHER.hashing_material = property(lambda self: plugin.call("builder_api___fullcipher_hashing_material", _wire_pack(self)))

# ── CounterPartySECRET :: AloecryptHashable ──

CounterPartySECRET.hash = property(lambda self: plugin.call("builder_api___counterpartysecret_hash", _wire_pack(self)))
CounterPartySECRET.hashing_material = property(lambda self: plugin.call("builder_api___counterpartysecret_hashing_material", _wire_pack(self)))

# ── PartyCHALLENGE :: AloecryptHashable ──

PartyCHALLENGE.hash = property(lambda self: plugin.call("builder_api___partychallenge_hash", _wire_pack(self)))
PartyCHALLENGE.hashing_material = property(lambda self: plugin.call("builder_api___partychallenge_hashing_material", _wire_pack(self)))

# ── PartyRESPONSE :: AloecryptHashable ──

PartyRESPONSE.hash = property(lambda self: plugin.call("builder_api___partyresponse_hash", _wire_pack(self)))
PartyRESPONSE.hashing_material = property(lambda self: plugin.call("builder_api___partyresponse_hashing_material", _wire_pack(self)))

# ── CounterPartyCHALLENGE :: AloecryptHashable ──

CounterPartyCHALLENGE.hash = property(lambda self: plugin.call("builder_api___counterpartychallenge_hash", _wire_pack(self)))
CounterPartyCHALLENGE.hashing_material = property(lambda self: plugin.call("builder_api___counterpartychallenge_hashing_material", _wire_pack(self)))

# ── FromSecretsInput :: AloecryptHashable ──

FromSecretsInput.hash = property(lambda self: plugin.call("builder_api___fromsecretsinput_hash", _wire_pack(self)))
FromSecretsInput.hashing_material = property(lambda self: plugin.call("builder_api___fromsecretsinput_hashing_material", _wire_pack(self)))

# ── SessionBuilder :: AloecryptHashable ──

SessionBuilder.hash = property(lambda self: plugin.call("builder_api___sessionbuilder_hash", _wire_pack(self)))
SessionBuilder.hashing_material = property(lambda self: plugin.call("builder_api___sessionbuilder_hashing_material", _wire_pack(self)))

# ── MsgHELLO :: AloecryptHashable ──

MsgHELLO.hash = property(lambda self: plugin.call("message_api___msghello_hash", _wire_pack(self)))
MsgHELLO.hashing_material = property(lambda self: plugin.call("message_api___msghello_hashing_material", _wire_pack(self)))

# ── MsgSYN :: AloecryptHashable ──

MsgSYN.hash = property(lambda self: plugin.call("message_api___msgsyn_hash", _wire_pack(self)))
MsgSYN.hashing_material = property(lambda self: plugin.call("message_api___msgsyn_hashing_material", _wire_pack(self)))

# ── MsgACK :: AloecryptHashable ──

MsgACK.hash = property(lambda self: plugin.call("message_api___msgack_hash", _wire_pack(self)))
MsgACK.hashing_material = property(lambda self: plugin.call("message_api___msgack_hashing_material", _wire_pack(self)))

# ── MsgSYNACK :: AloecryptHashable ──

MsgSYNACK.hash = property(lambda self: plugin.call("message_api___msgsynack_hash", _wire_pack(self)))
MsgSYNACK.hashing_material = property(lambda self: plugin.call("message_api___msgsynack_hashing_material", _wire_pack(self)))

# ── MsgWELCOME :: AloecryptHashable ──

MsgWELCOME.hash = property(lambda self: plugin.call("message_api___msgwelcome_hash", _wire_pack(self)))
MsgWELCOME.hashing_material = property(lambda self: plugin.call("message_api___msgwelcome_hashing_material", _wire_pack(self)))

# ── Party :: AloecryptHashable ──

Party.hash = property(lambda self: plugin.call("party_api___party_hash", _wire_pack(self)))
Party.hashing_material = property(lambda self: plugin.call("party_api___party_hashing_material", _wire_pack(self)))

# ── CounterParty :: AloecryptHashable ──

CounterParty.hash = property(lambda self: plugin.call("party_api___counterparty_hash", _wire_pack(self)))
CounterParty.hashing_material = property(lambda self: plugin.call("party_api___counterparty_hashing_material", _wire_pack(self)))

# ── AloecryptSession :: AloecryptHashable ──

AloecryptSession.hash = property(lambda self: plugin.call("session_api___aloecryptsession_hash", _wire_pack(self)))
AloecryptSession.hashing_material = property(lambda self: plugin.call("session_api___aloecryptsession_hashing_material", _wire_pack(self)))

# ── XAloecryptSession :: AloecryptXHashable ──

XAloecryptSession.hash = property(lambda self: plugin.call("session_api___xaloecryptsession_hash", _wire_pack(self)))
XAloecryptSession.x_hash = property(lambda self: plugin.call("session_api___xaloecryptsession_x_hash", _wire_pack(self)))
XAloecryptSession.x_hashing_material = property(lambda self: plugin.call("session_api___xaloecryptsession_x_hashing_material", _wire_pack(self)))

# ── AloecryptSession :: AloecryptPasswordPEM ──

AloecryptSession.pem_hdr_tag = staticmethod(lambda: plugin.call("session_api___aloecryptsession_pem_hdr_tag", _wire_pack()).decode())
AloecryptSession.pem_ftr_tag = staticmethod(lambda: plugin.call("session_api___aloecryptsession_pem_ftr_tag", _wire_pack()).decode())
AloecryptSession.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("session_api___aloecryptsession_pem_sz", _wire_pack()), 'little'))
AloecryptSession.x_pem = lambda self, password, salt: plugin.call("session_api___aloecryptsession_x_pem", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)).decode()
AloecryptSession.x_loads = classmethod(lambda cls, pem, password, salt: AloecryptSession.from_wire_bytes(plugin.call("session_api___aloecryptsession_x_loads", _wire_pack(_VarStr(pem), _VarBytes(password), _VarBytes(salt)))))
AloecryptSession.x_pub_loads = staticmethod(lambda pem: CounterParty.from_wire_bytes(plugin.call("session_api___aloecryptsession_x_pub_loads", _wire_pack(_VarStr(pem)))))

# ── AloecryptSession :: AloecryptPasswordLockable ──

AloecryptSession.lock_with_password = lambda self, password, salt: XAloecryptSession.from_wire_bytes(plugin.call("session_api___aloecryptsession_lock_with_password", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)))
AloecryptSession.unlock_with_password = classmethod(lambda cls, x_obj, password, salt: AloecryptSession.from_wire_bytes(plugin.call("session_api___aloecryptsession_unlock_with_password", _wire_pack(x_obj, _VarBytes(password), _VarBytes(salt)))))

# ── Party :: AloecryptPasswordLockable ──

Party.lock_with_password = lambda self, password, salt: XParty.from_wire_bytes(plugin.call("party_api___party_lock_with_password", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)))
Party.unlock_with_password = classmethod(lambda cls, x_obj, password, salt: Party.from_wire_bytes(plugin.call("party_api___party_unlock_with_password", _wire_pack(x_obj, _VarBytes(password), _VarBytes(salt)))))

# ── CounterParty :: AloecryptPasswordLockable ──

CounterParty.lock_with_password = lambda self, password, salt: XCounterParty.from_wire_bytes(plugin.call("party_api___counterparty_lock_with_password", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)))
CounterParty.unlock_with_password = classmethod(lambda cls, x_obj, password, salt: CounterParty.from_wire_bytes(plugin.call("party_api___counterparty_unlock_with_password", _wire_pack(x_obj, _VarBytes(password), _VarBytes(salt)))))

# ── XAloecryptSession :: AloecryptPEM ──

XAloecryptSession.pem_hdr_tag = staticmethod(lambda: plugin.call("session_api___xaloecryptsession_pem_hdr_tag", _wire_pack()).decode())
XAloecryptSession.pem_ftr_tag = staticmethod(lambda: plugin.call("session_api___xaloecryptsession_pem_ftr_tag", _wire_pack()).decode())
XAloecryptSession.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("session_api___xaloecryptsession_pem_sz", _wire_pack()), 'little'))
XAloecryptSession.pem = property(lambda self: plugin.call("session_api___xaloecryptsession_pem", _wire_pack(self)).decode())
XAloecryptSession.loads = classmethod(lambda cls, pem: XAloecryptSession.from_wire_bytes(plugin.call("session_api___xaloecryptsession_loads", _wire_pack(_VarStr(pem)))))

# ── MsgHELLO :: AloecryptPEM ──

MsgHELLO.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msghello_pem_hdr_tag", _wire_pack()).decode())
MsgHELLO.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msghello_pem_ftr_tag", _wire_pack()).decode())
MsgHELLO.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msghello_pem_sz", _wire_pack()), 'little'))
MsgHELLO.pem = property(lambda self: plugin.call("message_api___msghello_pem", _wire_pack(self)).decode())
MsgHELLO.loads = classmethod(lambda cls, pem: MsgHELLO.from_wire_bytes(plugin.call("message_api___msghello_loads", _wire_pack(_VarStr(pem)))))

# ── MsgSYN :: AloecryptPEM ──

MsgSYN.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msgsyn_pem_hdr_tag", _wire_pack()).decode())
MsgSYN.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msgsyn_pem_ftr_tag", _wire_pack()).decode())
MsgSYN.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgsyn_pem_sz", _wire_pack()), 'little'))
MsgSYN.pem = property(lambda self: plugin.call("message_api___msgsyn_pem", _wire_pack(self)).decode())
MsgSYN.loads = classmethod(lambda cls, pem: MsgSYN.from_wire_bytes(plugin.call("message_api___msgsyn_loads", _wire_pack(_VarStr(pem)))))

# ── MsgACK :: AloecryptPEM ──

MsgACK.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msgack_pem_hdr_tag", _wire_pack()).decode())
MsgACK.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msgack_pem_ftr_tag", _wire_pack()).decode())
MsgACK.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgack_pem_sz", _wire_pack()), 'little'))
MsgACK.pem = property(lambda self: plugin.call("message_api___msgack_pem", _wire_pack(self)).decode())
MsgACK.loads = classmethod(lambda cls, pem: MsgACK.from_wire_bytes(plugin.call("message_api___msgack_loads", _wire_pack(_VarStr(pem)))))

# ── MsgSYNACK :: AloecryptPEM ──

MsgSYNACK.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msgsynack_pem_hdr_tag", _wire_pack()).decode())
MsgSYNACK.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msgsynack_pem_ftr_tag", _wire_pack()).decode())
MsgSYNACK.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgsynack_pem_sz", _wire_pack()), 'little'))
MsgSYNACK.pem = property(lambda self: plugin.call("message_api___msgsynack_pem", _wire_pack(self)).decode())
MsgSYNACK.loads = classmethod(lambda cls, pem: MsgSYNACK.from_wire_bytes(plugin.call("message_api___msgsynack_loads", _wire_pack(_VarStr(pem)))))

# ── MsgWELCOME :: AloecryptPEM ──

MsgWELCOME.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msgwelcome_pem_hdr_tag", _wire_pack()).decode())
MsgWELCOME.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msgwelcome_pem_ftr_tag", _wire_pack()).decode())
MsgWELCOME.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgwelcome_pem_sz", _wire_pack()), 'little'))
MsgWELCOME.pem = property(lambda self: plugin.call("message_api___msgwelcome_pem", _wire_pack(self)).decode())
MsgWELCOME.loads = classmethod(lambda cls, pem: MsgWELCOME.from_wire_bytes(plugin.call("message_api___msgwelcome_loads", _wire_pack(_VarStr(pem)))))

# ── MsgGOODBYE :: AloecryptPEM ──

MsgGOODBYE.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msggoodbye_pem_hdr_tag", _wire_pack()).decode())
MsgGOODBYE.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msggoodbye_pem_ftr_tag", _wire_pack()).decode())
MsgGOODBYE.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msggoodbye_pem_sz", _wire_pack()), 'little'))
MsgGOODBYE.pem = property(lambda self: plugin.call("message_api___msggoodbye_pem", _wire_pack(self)).decode())
MsgGOODBYE.loads = classmethod(lambda cls, pem: MsgGOODBYE.from_wire_bytes(plugin.call("message_api___msggoodbye_loads", _wire_pack(_VarStr(pem)))))

# ── MsgRETRY :: AloecryptPEM ──

MsgRETRY.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msgretry_pem_hdr_tag", _wire_pack()).decode())
MsgRETRY.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msgretry_pem_ftr_tag", _wire_pack()).decode())
MsgRETRY.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgretry_pem_sz", _wire_pack()), 'little'))
MsgRETRY.pem = property(lambda self: plugin.call("message_api___msgretry_pem", _wire_pack(self)).decode())
MsgRETRY.loads = classmethod(lambda cls, pem: MsgRETRY.from_wire_bytes(plugin.call("message_api___msgretry_loads", _wire_pack(_VarStr(pem)))))

# ── MsgRESYN :: AloecryptPEM ──

MsgRESYN.pem_hdr_tag = staticmethod(lambda: plugin.call("message_api___msgresyn_pem_hdr_tag", _wire_pack()).decode())
MsgRESYN.pem_ftr_tag = staticmethod(lambda: plugin.call("message_api___msgresyn_pem_ftr_tag", _wire_pack()).decode())
MsgRESYN.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("message_api___msgresyn_pem_sz", _wire_pack()), 'little'))
MsgRESYN.pem = property(lambda self: plugin.call("message_api___msgresyn_pem", _wire_pack(self)).decode())
MsgRESYN.loads = classmethod(lambda cls, pem: MsgRESYN.from_wire_bytes(plugin.call("message_api___msgresyn_loads", _wire_pack(_VarStr(pem)))))

# ── AloecryptSession :: IAloecryptSession ──

AloecryptSession.encrypt = lambda self, plaintext: plugin.call("session_api___aloecryptsession_encrypt", _wire_pack(self, _VarBytes(plaintext)))
AloecryptSession.decrypt = lambda self, ciphertext: plugin.call("session_api___aloecryptsession_decrypt", _wire_pack(self, _VarBytes(ciphertext)))
AloecryptSession.from_secrets = classmethod(lambda cls, party_stable_secret, party_session_secret, party_session_signature, party_nonce, party_address, counterparty_stable_secret, counterparty_session_secret, counterparty_signature, counterparty_nonce, counterparty_address, session_salt: AloecryptSession.from_wire_bytes(plugin.call("session_api___aloecryptsession_from_secrets", _wire_pack(party_stable_secret, party_session_secret, party_session_signature, party_nonce, party_address, counterparty_stable_secret, counterparty_session_secret, counterparty_signature, counterparty_nonce, counterparty_address, session_salt))))

# ── XDilithiumSigner :: AloecryptAddressable ──

XDilithiumSigner.generation = property(lambda self: int.from_bytes(plugin.call("signatory_api___xdilithiumsigner_generation", _wire_pack(self)), 'little'))
XDilithiumSigner.address = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_address", _wire_pack(self)))
XDilithiumSigner.auth_address = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_auth_address", _wire_pack(self)))
XDilithiumSigner.root_address = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_root_address", _wire_pack(self)))
XDilithiumSigner.addressing_material = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_addressing_material", _wire_pack(self)))
XDilithiumSigner.auth_addressing_material = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_auth_addressing_material", _wire_pack(self)))
XDilithiumSigner.is_root = property(lambda self: bool(plugin.call("signatory_api___xdilithiumsigner_is_root", _wire_pack(self))[0]))

# ── DilithiumSigner :: AloecryptAddressable ──

DilithiumSigner.generation = property(lambda self: int.from_bytes(plugin.call("signatory_api___dilithiumsigner_generation", _wire_pack(self)), 'little'))
DilithiumSigner.address = property(lambda self: plugin.call("signatory_api___dilithiumsigner_address", _wire_pack(self)))
DilithiumSigner.auth_address = property(lambda self: plugin.call("signatory_api___dilithiumsigner_auth_address", _wire_pack(self)))
DilithiumSigner.root_address = property(lambda self: plugin.call("signatory_api___dilithiumsigner_root_address", _wire_pack(self)))
DilithiumSigner.addressing_material = property(lambda self: plugin.call("signatory_api___dilithiumsigner_addressing_material", _wire_pack(self)))
DilithiumSigner.auth_addressing_material = property(lambda self: plugin.call("signatory_api___dilithiumsigner_auth_addressing_material", _wire_pack(self)))
DilithiumSigner.is_root = property(lambda self: bool(plugin.call("signatory_api___dilithiumsigner_is_root", _wire_pack(self))[0]))

# ── DilithiumVerifier :: AloecryptAddressable ──

DilithiumVerifier.generation = property(lambda self: int.from_bytes(plugin.call("signatory_api___dilithiumverifier_generation", _wire_pack(self)), 'little'))
DilithiumVerifier.address = property(lambda self: plugin.call("signatory_api___dilithiumverifier_address", _wire_pack(self)))
DilithiumVerifier.auth_address = property(lambda self: plugin.call("signatory_api___dilithiumverifier_auth_address", _wire_pack(self)))
DilithiumVerifier.root_address = property(lambda self: plugin.call("signatory_api___dilithiumverifier_root_address", _wire_pack(self)))
DilithiumVerifier.addressing_material = property(lambda self: plugin.call("signatory_api___dilithiumverifier_addressing_material", _wire_pack(self)))
DilithiumVerifier.auth_addressing_material = property(lambda self: plugin.call("signatory_api___dilithiumverifier_auth_addressing_material", _wire_pack(self)))
DilithiumVerifier.is_root = property(lambda self: bool(plugin.call("signatory_api___dilithiumverifier_is_root", _wire_pack(self))[0]))

# ── XDilithiumSigner :: AloecryptEmpty ──

XDilithiumSigner.empty = classmethod(lambda cls: XDilithiumSigner.from_wire_bytes(plugin.call("signatory_api___xdilithiumsigner_empty", b"")))
XDilithiumSigner.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("signatory_api___xdilithiumsigner_byte_sz", _wire_pack()), 'little'))
XDilithiumSigner.to_bytes = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_to_bytes", _wire_pack(self)))
XDilithiumSigner.from_bytes = classmethod(lambda cls, bytes: XDilithiumSigner.from_wire_bytes(plugin.call("signatory_api___xdilithiumsigner_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── DilithiumSigner :: AloecryptEmpty ──

DilithiumSigner.empty = classmethod(lambda cls: DilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_empty", b"")))
DilithiumSigner.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("signatory_api___dilithiumsigner_byte_sz", _wire_pack()), 'little'))
DilithiumSigner.to_bytes = property(lambda self: plugin.call("signatory_api___dilithiumsigner_to_bytes", _wire_pack(self)))
DilithiumSigner.from_bytes = classmethod(lambda cls, bytes: DilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── DilithiumVerifier :: AloecryptEmpty ──

DilithiumVerifier.empty = classmethod(lambda cls: DilithiumVerifier.from_wire_bytes(plugin.call("signatory_api___dilithiumverifier_empty", b"")))
DilithiumVerifier.byte_sz = staticmethod(lambda: int.from_bytes(plugin.call("signatory_api___dilithiumverifier_byte_sz", _wire_pack()), 'little'))
DilithiumVerifier.to_bytes = property(lambda self: plugin.call("signatory_api___dilithiumverifier_to_bytes", _wire_pack(self)))
DilithiumVerifier.from_bytes = classmethod(lambda cls, bytes: DilithiumVerifier.from_wire_bytes(plugin.call("signatory_api___dilithiumverifier_from_bytes", _wire_pack(_VarBytes(bytes)))))

# ── XDilithiumSigner :: AloecryptXHashable ──

XDilithiumSigner.hash = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_hash", _wire_pack(self)))
XDilithiumSigner.x_hash = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_x_hash", _wire_pack(self)))
XDilithiumSigner.x_hashing_material = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_x_hashing_material", _wire_pack(self)))

# ── DilithiumVerifier :: AloecryptHashable ──

DilithiumVerifier.hash = property(lambda self: plugin.call("signatory_api___dilithiumverifier_hash", _wire_pack(self)))
DilithiumVerifier.hashing_material = property(lambda self: plugin.call("signatory_api___dilithiumverifier_hashing_material", _wire_pack(self)))

# ── DilithiumSigner :: AloecryptHashable ──

DilithiumSigner.hash = property(lambda self: plugin.call("signatory_api___dilithiumsigner_hash", _wire_pack(self)))
DilithiumSigner.hashing_material = property(lambda self: plugin.call("signatory_api___dilithiumsigner_hashing_material", _wire_pack(self)))

# ── DilithiumSigner :: AloecryptHashableKeypair ──

DilithiumSigner.pub_hash = property(lambda self: plugin.call("signatory_api___dilithiumsigner_pub_hash", _wire_pack(self)))
DilithiumSigner.priv_hash = property(lambda self: plugin.call("signatory_api___dilithiumsigner_priv_hash", _wire_pack(self)))

# ── XDilithiumSigner :: AloecryptHashableKeypair ──

XDilithiumSigner.pub_hash = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_pub_hash", _wire_pack(self)))
XDilithiumSigner.priv_hash = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_priv_hash", _wire_pack(self)))

# ── DilithiumVerifier :: AloecryptHashablePubkey ──

DilithiumVerifier.pub_hash = property(lambda self: plugin.call("signatory_api___dilithiumverifier_pub_hash", _wire_pack(self)))

# ── DilithiumSigner :: AloecryptPasswordPEM ──

DilithiumSigner.pem_hdr_tag = staticmethod(lambda: plugin.call("signatory_api___dilithiumsigner_pem_hdr_tag", _wire_pack()).decode())
DilithiumSigner.pem_ftr_tag = staticmethod(lambda: plugin.call("signatory_api___dilithiumsigner_pem_ftr_tag", _wire_pack()).decode())
DilithiumSigner.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("signatory_api___dilithiumsigner_pem_sz", _wire_pack()), 'little'))
DilithiumSigner.x_pem = lambda self, password, salt: plugin.call("signatory_api___dilithiumsigner_x_pem", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)).decode()
DilithiumSigner.x_loads = classmethod(lambda cls, pem, password, salt: DilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_x_loads", _wire_pack(_VarStr(pem), _VarBytes(password), _VarBytes(salt)))))
DilithiumSigner.x_pub_loads = staticmethod(lambda pem: DilithiumVerifier.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_x_pub_loads", _wire_pack(_VarStr(pem)))))

# ── DilithiumSigner :: AloecryptPasswordLockable ──

DilithiumSigner.lock_with_password = lambda self, password, salt: XDilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_lock_with_password", _wire_pack(self, _VarBytes(password), _VarBytes(salt), -1)))
DilithiumSigner.unlock_with_password = classmethod(lambda cls, x_obj, password, salt: DilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_unlock_with_password", _wire_pack(x_obj, _VarBytes(password), _VarBytes(salt)))))

# ── XDilithiumSigner :: AloecryptPEM ──

XDilithiumSigner.pem_hdr_tag = staticmethod(lambda: plugin.call("signatory_api___xdilithiumsigner_pem_hdr_tag", _wire_pack()).decode())
XDilithiumSigner.pem_ftr_tag = staticmethod(lambda: plugin.call("signatory_api___xdilithiumsigner_pem_ftr_tag", _wire_pack()).decode())
XDilithiumSigner.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("signatory_api___xdilithiumsigner_pem_sz", _wire_pack()), 'little'))
XDilithiumSigner.pem = property(lambda self: plugin.call("signatory_api___xdilithiumsigner_pem", _wire_pack(self)).decode())
XDilithiumSigner.loads = classmethod(lambda cls, pem: XDilithiumSigner.from_wire_bytes(plugin.call("signatory_api___xdilithiumsigner_loads", _wire_pack(_VarStr(pem)))))

# ── DilithiumVerifier :: AloecryptPEM ──

DilithiumVerifier.pem_hdr_tag = staticmethod(lambda: plugin.call("signatory_api___dilithiumverifier_pem_hdr_tag", _wire_pack()).decode())
DilithiumVerifier.pem_ftr_tag = staticmethod(lambda: plugin.call("signatory_api___dilithiumverifier_pem_ftr_tag", _wire_pack()).decode())
DilithiumVerifier.pem_sz = staticmethod(lambda: int.from_bytes(plugin.call("signatory_api___dilithiumverifier_pem_sz", _wire_pack()), 'little'))
DilithiumVerifier.pem = property(lambda self: plugin.call("signatory_api___dilithiumverifier_pem", _wire_pack(self)).decode())
DilithiumVerifier.loads = classmethod(lambda cls, pem: DilithiumVerifier.from_wire_bytes(plugin.call("signatory_api___dilithiumverifier_loads", _wire_pack(_VarStr(pem)))))

# ── DilithiumSigner :: AloecryptSignable ──

DilithiumSigner.signature = property(lambda self: plugin.call("signatory_api___dilithiumsigner_signature", _wire_pack(self)))
DilithiumSigner.signed_by = property(lambda self: plugin.call("signatory_api___dilithiumsigner_signed_by", _wire_pack(self)))
DilithiumSigner.signing_material = property(lambda self: plugin.call("signatory_api___dilithiumsigner_signing_material", _wire_pack(self)))

# ── DilithiumVerifier :: AloecryptSignable ──

DilithiumVerifier.signature = property(lambda self: plugin.call("signatory_api___dilithiumverifier_signature", _wire_pack(self)))
DilithiumVerifier.signed_by = property(lambda self: plugin.call("signatory_api___dilithiumverifier_signed_by", _wire_pack(self)))
DilithiumVerifier.signing_material = property(lambda self: plugin.call("signatory_api___dilithiumverifier_signing_material", _wire_pack(self)))

# ── DilithiumSigner :: AloecryptSigner ──

DilithiumSigner.may_sign = property(lambda self: bool(plugin.call("signatory_api___dilithiumsigner_may_sign", _wire_pack(self))[0]))
DilithiumSigner.signing_key = property(lambda self: plugin.call("signatory_api___dilithiumsigner_signing_key", _wire_pack(self)))
DilithiumSigner.sign = lambda self, signing_material: plugin.call("signatory_api___dilithiumsigner_sign", _wire_pack(self, _VarBytes(signing_material)))

# ── DilithiumSigner :: IDilithiumSigner ──

DilithiumSigner.new = classmethod(lambda cls: DilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_new", _wire_pack(-1))))
DilithiumSigner.canonical_dilithium_signer = lambda self, cannonical_idx, dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh: DilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_canonical_dilithium_signer", _wire_pack(self, _VarBytes(cannonical_idx), dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh)))
DilithiumSigner.create_dilithium_signer = lambda self, dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh: DilithiumSigner.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_create_dilithium_signer", _wire_pack(self, dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh, -1)))
DilithiumSigner.canonical_kyber_kem = lambda self, cannonical_idx, dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh: KyberFullKEM.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_canonical_kyber_kem", _wire_pack(self, _VarBytes(cannonical_idx), dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh)))
DilithiumSigner.create_kyber_kem = lambda self, dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh: KyberFullKEM.from_wire_bytes(plugin.call("signatory_api___dilithiumsigner_create_kyber_kem", _wire_pack(self, dlt_active_from, dlt_expires_at, dlt_refresh_count, dlt_max_refresh, -1)))

# ── DilithiumVerifier :: AloecryptVerifier ──

DilithiumVerifier.may_verify = property(lambda self: bool(plugin.call("signatory_api___dilithiumverifier_may_verify", _wire_pack(self))[0]))
DilithiumVerifier.verifying_key = property(lambda self: plugin.call("signatory_api___dilithiumverifier_verifying_key", _wire_pack(self)))
DilithiumVerifier.verify = lambda self, signing_material, sig_bytes: plugin.call("signatory_api___dilithiumverifier_verify", _wire_pack(self, _VarBytes(signing_material), sig_bytes))

# ── DilithiumSigner :: AloecryptVerifier ──

DilithiumSigner.may_verify = property(lambda self: bool(plugin.call("signatory_api___dilithiumsigner_may_verify", _wire_pack(self))[0]))
DilithiumSigner.verifying_key = property(lambda self: plugin.call("signatory_api___dilithiumsigner_verifying_key", _wire_pack(self)))
DilithiumSigner.verify = lambda self, signing_material, sig_bytes: plugin.call("signatory_api___dilithiumsigner_verify", _wire_pack(self, _VarBytes(signing_material), sig_bytes))
